<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_File-emo-b10-4a8</name>
   <tag></tag>
   <elementGuidId>67ab252b-5545-4341-9356-3a3108180108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu017f > div.smart-container > #menu017fMainContainer > #menuItemsGroup4d11 > div.smart-menu-item-label-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//smart-menu-items-group[@id='menuItemsGroup4d11']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>div >> internal:has-text=&quot;File&quot;i >> nth=2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df64733d-b50c-47d0-8e55-60bd22964449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>smart-menu-item-label-container</value>
      <webElementGuid>dd78f08b-6959-48e4-8085-2f57049918c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                File
                </value>
      <webElementGuid>7108072d-2870-4608-a6de-23649ffb216e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/smart-menu[@id=&quot;menu017f&quot;]/div[@class=&quot;smart-container&quot;]/div[@id=&quot;menu017fMainContainer&quot;]/smart-menu-items-group[@id=&quot;menuItemsGroup4d11&quot;]/div[@class=&quot;smart-menu-item-label-container&quot;]</value>
      <webElementGuid>d2f44435-f1fe-4fa8-a67d-7c0f4ae2e8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>katalon:smartLocator</name>
      <type>Main</type>
      <value>div >> internal:has-text=&quot;File&quot;i >> nth=2</value>
      <webElementGuid>c7c5830b-b16f-48df-8410-1e2d4cdab108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Menu Shadow DOM Demo/smart-ui-menu_smart-ui-component-OM Demo-b10</value>
      <webElementGuid>004566f9-7e43-4c93-bc3a-22156622ad58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b878e2ae-0a00-45c7-a503-17e2be92b220</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//smart-menu-items-group[@id='menuItemsGroup4d11']/div</value>
      <webElementGuid>eb2691ee-7657-4a3a-aa9b-0340dee26c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                File
                ' or . = '
                File
                ')]</value>
      <webElementGuid>b8c044fe-18f4-4630-8f39-98ca888bde8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
