<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NewCtrlN-emo-b10-2b3</name>
   <tag></tag>
   <elementGuidId>5b2db0fb-7fb8-45b8-8857-7dcbf7761358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu017f > div.smart-container > #menu017fMainContainer > #menuItemsGroup4d11 > #menuItemsGroup4d11Container > div.smart-menu-item-container > #menuItem3ccb > div.smart-menu-item-label-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//smart-menu-item[@id='menuItem3ccb']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>internal:text=&quot;NewCtrl+N&quot;i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19d2b792-7a94-4f1c-a456-ab4414a4111d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>smart-menu-item-label-container</value>
      <webElementGuid>e700d458-1d43-4401-b4c6-354aad6f060c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NewCtrl+N</value>
      <webElementGuid>4a384f44-c0c2-4555-b152-3c8677ce7a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/smart-menu[@id=&quot;menu017f&quot;]/div[@class=&quot;smart-container&quot;]/div[@id=&quot;menu017fMainContainer&quot;]/smart-menu-items-group[@id=&quot;menuItemsGroup4d11&quot;]/div[@id=&quot;menuItemsGroup4d11Container&quot;]/div[@class=&quot;smart-menu-item-container&quot;]/smart-menu-item[@id=&quot;menuItem3ccb&quot;]/div[@class=&quot;smart-menu-item-label-container&quot;]</value>
      <webElementGuid>682fd94b-ead0-49ff-865b-649607f719c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>katalon:smartLocator</name>
      <type>Main</type>
      <value>internal:text=&quot;NewCtrl+N&quot;i</value>
      <webElementGuid>ac5c1d0d-c807-4ea3-bb51-3976de1b94e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Menu Shadow DOM Demo/smart-ui-menu_smart-ui-component-OM Demo-b10</value>
      <webElementGuid>25f97145-826c-44e8-ad42-26ab4a85ca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e148ff57-1100-4d8f-b36e-c7b31908de48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//smart-menu-item[@id='menuItem3ccb']/div</value>
      <webElementGuid>2620649e-99f4-4026-9695-4526d029ad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NewCtrl+N' or . = 'NewCtrl+N')]</value>
      <webElementGuid>092452e2-2a63-417b-a81c-047cdeca9576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
